#include <algorithm>
#include <cstdlib>
#include <vector>

class Solution {
  public:
    long long unifyCost(std::vector<int> &nums) {
        // Making every element equal to one target y costs sum |nums[i] - y|,
        // a convex function of y that is flat between the two middle elements
        // when n is even — so an optimal y always sits next to the median:
        // the largest palindrome <= median or the smallest palindrome >=
        // median. All 109998 palindromes below 10^9 are generated by
        // mirroring each half 1..99999 (odd and even length), then the
        // bracketing pair of the median is found by binary search. Totals
        // are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
        // typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
        std::vector<long long> pals;
        pals.reserve(220000);
        for (long long half = 1; half < 100000; ++half) {
            long long odd = half;
            for (long long t = half / 10; t > 0; t /= 10) {
                odd = odd * 10 + t % 10;
            }
            long long even = half;
            for (long long t = half; t > 0; t /= 10) {
                even = even * 10 + t % 10;
            }
            if (odd < 1000000000LL) {
                pals.push_back(odd);
            }
            if (even < 1000000000LL) {
                pals.push_back(even);
            }
        }
        std::sort(pals.begin(), pals.end());
        std::sort(nums.begin(), nums.end());
        long long median = nums[nums.size() / 2];
        int j = std::lower_bound(pals.begin(), pals.end(), median) - pals.begin();
        auto cost = [&](long long y) {
            long long total = 0;
            for (int v : nums) {
                total += std::abs(v - y);
            }
            return total;
        };
        if (j < static_cast<int>(pals.size()) && pals[j] == median) {
            return cost(median);
        }
        long long best = cost(pals[j - 1]);
        if (j < static_cast<int>(pals.size())) {
            best = std::min(best, cost(pals[j]));
        }
        return best;
    }
};
