import "sort"

func unifyCost(nums []int) int64 {
	// Making every element equal to one target y costs sum |nums[i] - y|,
	// a convex function of y that is flat between the two middle elements
	// when n is even — so an optimal y always sits next to the median:
	// the largest palindrome <= median or the smallest palindrome >=
	// median. All 109998 palindromes below 10^9 are generated by
	// mirroring each half 1..99999 (odd and even length), then the
	// bracketing pair of the median is found by binary search. Totals
	// are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
	// typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
	pals := make([]int64, 0, 220000)
	for half := int64(1); half < 100000; half++ {
		odd := half
		for t := half / 10; t > 0; t /= 10 {
			odd = odd*10 + t%10
		}
		even := half
		for t := half; t > 0; t /= 10 {
			even = even*10 + t%10
		}
		if odd < 1000000000 {
			pals = append(pals, odd)
		}
		if even < 1000000000 {
			pals = append(pals, even)
		}
	}
	sort.Slice(pals, func(i, j int) bool { return pals[i] < pals[j] })
	sort.Ints(nums)
	median := int64(nums[len(nums)/2])
	j := sort.Search(len(pals), func(i int) bool { return pals[i] >= median })
	cost := func(y int64) int64 {
		total := int64(0)
		for _, v := range nums {
			diff := int64(v) - y
			if diff < 0 {
				diff = -diff
			}
			total += diff
		}
		return total
	}
	if j < len(pals) && pals[j] == median {
		return cost(median)
	}
	best := cost(pals[j-1])
	if j < len(pals) {
		if c := cost(pals[j]); c < best {
			best = c
		}
	}
	return best
}
