import java.util.Arrays;

class Solution {

    public long unifyCost(int[] nums) {
        // Making every element equal to one target y costs sum |nums[i] - y|,
        // a convex function of y that is flat between the two middle elements
        // when n is even — so an optimal y always sits next to the median:
        // the largest palindrome <= median or the smallest palindrome >=
        // median. All 109998 palindromes below 10^9 are generated by
        // mirroring each half 1..99999 (odd and even length), then the
        // bracketing pair of the median is found by binary search. Totals
        // are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
        // typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
        long[] pals = new long[220000];
        int count = 0;
        for (long half = 1; half < 100000; half++) {
            long odd = half;
            for (long t = half / 10; t > 0; t /= 10) {
                odd = odd * 10 + (t % 10);
            }
            long even = half;
            for (long t = half; t > 0; t /= 10) {
                even = even * 10 + (t % 10);
            }
            if (odd < 1000000000L) {
                pals[count++] = odd;
            }
            if (even < 1000000000L) {
                pals[count++] = even;
            }
        }
        Arrays.sort(pals, 0, count);
        Arrays.sort(nums);
        long median = nums[nums.length / 2];
        int j = Arrays.binarySearch(pals, 0, count, median);
        if (j >= 0) {
            return costOf(nums, median);
        }
        j = -(j + 1);
        long best = costOf(nums, pals[j - 1]);
        if (j < count) {
            best = Math.min(best, costOf(nums, pals[j]));
        }
        return best;
    }

    private long costOf(int[] nums, long y) {
        long total = 0;
        for (int v : nums) {
            total += Math.abs(v - y);
        }
        return total;
    }
}
