function unifyCost(nums: number[]): number {
    // Making every element equal to one target y costs sum |nums[i] - y|,
    // a convex function of y that is flat between the two middle elements
    // when n is even — so an optimal y always sits next to the median:
    // the largest palindrome <= median or the smallest palindrome >=
    // median. All 109998 palindromes below 10^9 are generated by
    // mirroring each half 1..99999 (odd and even length), then the
    // bracketing pair of the median is found by binary search. Totals
    // are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
    // typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
    const pals: number[] = [];
    for (let half = 1; half < 100000; half++) {
        let odd = half;
        for (let t = Math.floor(half / 10); t > 0; t = Math.floor(t / 10)) {
            odd = odd * 10 + (t % 10);
        }
        let even = half;
        for (let t = half; t > 0; t = Math.floor(t / 10)) {
            even = even * 10 + (t % 10);
        }
        if (odd < 1000000000) {
            pals.push(odd);
        }
        if (even < 1000000000) {
            pals.push(even);
        }
    }
    pals.sort((a, b) => a - b);
    nums.sort((a, b) => a - b);
    const median = nums[Math.floor(nums.length / 2)];
    let lo = 0;
    let hi = pals.length;
    while (lo < hi) {
        const mid = (lo + hi) >> 1;
        if (pals[mid] < median) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    const cost = (y: number): number => {
        let total = 0;
        for (const v of nums) {
            total += Math.abs(v - y);
        }
        return total;
    };
    if (lo < pals.length && pals[lo] === median) {
        return cost(median);
    }
    let best = cost(pals[lo - 1]);
    if (lo < pals.length) {
        best = Math.min(best, cost(pals[lo]));
    }
    return best;
}
