impl Solution {
    pub fn minimum_cost(nums: Vec<i32>) -> i64 {
        // Making every element equal to one target y costs sum |nums[i] - y|,
        // a convex function of y that is flat between the two middle elements
        // when n is even — so an optimal y always sits next to the median:
        // the largest palindrome <= median or the smallest palindrome >=
        // median. All 109998 palindromes below 10^9 are generated by
        // mirroring each half 1..99999 (odd and even length), then the
        // bracketing pair of the median is found by binary search. Totals
        // are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
        // typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
        let mut pals: Vec<i64> = Vec::with_capacity(220000);
        for half in 1..100000i64 {
            let mut odd = half;
            let mut t = half / 10;
            while t > 0 {
                odd = odd * 10 + t % 10;
                t /= 10;
            }
            let mut even = half;
            let mut t = half;
            while t > 0 {
                even = even * 10 + t % 10;
                t /= 10;
            }
            if odd < 1000000000 {
                pals.push(odd);
            }
            if even < 1000000000 {
                pals.push(even);
            }
        }
        pals.sort_unstable();
        let mut nums = nums;
        nums.sort_unstable();
        let median = nums[nums.len() / 2] as i64;
        let j = pals.partition_point(|&p| p < median);
        let cost = |y: i64| -> i64 { nums.iter().map(|&v| (v as i64 - y).abs()).sum() };
        if j < pals.len() && pals[j] == median {
            return cost(median);
        }
        let mut best = cost(pals[j - 1]);
        if j < pals.len() {
            best = best.min(cost(pals[j]));
        }
        best
    }
}
