import bisect
from typing import List


class Solution:
    def minimumCost(self, nums: List[int]) -> int:
        # Making every element equal to one target y costs sum |nums[i] - y|,
        # a convex function of y that is flat between the two middle elements
        # when n is even — so an optimal y always sits next to the median:
        # the largest palindrome <= median or the smallest palindrome >=
        # median. All 109998 palindromes below 10^9 are generated by
        # mirroring each half 1..99999 (odd and even length), then the
        # bracketing pair of the median is found by binary search. Totals
        # are bounded by 10^5 * 10^9 = 10^14: 64-bit accumulators in the
        # typed languages, and 10^14 < 2^53 keeps JavaScript numbers exact.
        pals = []
        for half in range(1, 100000):
            digits = str(half)
            pals.append(int(digits + digits[-2::-1]))
            pals.append(int(digits + digits[::-1]))
        pals = sorted(p for p in pals if p < 10**9)
        nums = sorted(nums)
        median = nums[len(nums) // 2]
        j = bisect.bisect_left(pals, median)
        if j < len(pals) and pals[j] == median:
            return sum(abs(v - median) for v in nums)
        best = sum(abs(v - pals[j - 1]) for v in nums)
        if j < len(pals):
            best = min(best, sum(abs(v - pals[j]) for v in nums))
        return best
