#!/usr/bin/env python3
"""Regenerate problems-adapt/MAPPING.md from the adaptation ledger.

The ledger is the machine-readable record; this is the page a human
reads. It is also what cutover needs: submissions are keyed by slug, so
replacing the tree means rewriting those keys through this map.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEDGER = ROOT / ".adapt" / "ledger.json"
MAPPING = ROOT / "problems-adapt" / "MAPPING.md"

HEADER = """# Mapping — adapted problems to their sources

Generated by `scripts/adapt_mapping.py`; edit the ledger, not this file.

| ours | source | old API → new API | kind |
| ---- | ------ | ----------------- | ---- |
"""


def main() -> int:
    entries = json.loads(LEDGER.read_text(encoding="utf-8"))["entries"]
    rows = []
    for entry in sorted(entries, key=lambda e: e["id"]):
        api = ", ".join(f"`{old}` → `{new}`" for old, new in (entry.get("api") or {}).items())
        rows.append(
            f"| `{entry['adapted']}` | `{entry['source']}` | {api or '—'} | {entry.get('kind', '—')} |"
        )
    MAPPING.write_text(HEADER + "\n".join(rows) + "\n", encoding="utf-8")
    print(f"MAPPING.md: {len(rows)} adapted problems")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
